name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'  # Use a versão LTS recomendada

      - name: Display Node.js version
        run: node -v

      - name: Display npm version
        run: npm -v

      - name: Install npm dependencies
        run: npm install

      - name: Install Cypress
        run: npx cypress install

      - name: Start application
        run: npm start &
        env:
          CI: true

      - name: Wait for application to be ready
        run: sleep 15  # Ajuste o tempo conforme necessário

      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/**/*.js"
