name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'  # Versão LTS recomendada

      - name: Install npm dependencies
        run: npm install

      - name: Install Cypress
        run: npx cypress install

      - name: Start application
        run: npm start &
        env:
          CI: true  

      - name: Wait for application to load
        run: sleep 15

      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/**/*.js"
